AWSTemplateFormatVersion: '2010-09-09'
Description: CFN 201 Workshop - The root stack for Nested Stacks. (uksb-1qbkgojmn)
Parameters:
  AvailabilityZones:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Description: The list of Availability Zones to use for the subnets in the VPC.
    Default: eu-west-2a,eu-west-2b
  VPCName:
    Type: String
    Description: The name of the VPC.
    Default: cfn-workshop-vpc
  VPCCidr:
    Type: String
    Description: The CIDR block for the VPC.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
  PublicSubnet1Cidr:
    Type: String
    Description: The CIDR block for the public subnet located in Availability Zone
      1.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/24
  PublicSubnet2Cidr:
    Type: String
    Description: The CIDR block for the public subnet located in Availability Zone
      2.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.1.0/24
  EnvironmentType:
    Description: Specify the Environment type of the stack.
    Type: String
    Default: Test
    AllowedValues:
    - Dev
    - Test
    - Prod
    ConstraintDescription: Specify either Dev, Test or Prod.
Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-2.amazonaws.com/cfn-workshop-s3-s3bucket-1xluv23n1twtc/b944d5be77649fe74afbc9f33ee3b7b1.template
      TimeoutInMinutes: 20
      Parameters:
        AvailabilityZones:
          Fn::Join:
          - ','
          - Ref: AvailabilityZones
        VPCCidr:
          Ref: VPCCidr
        VPCName:
          Ref: VPCName
        PublicSubnetCidrs:
          Fn::Join:
          - ','
          - - Ref: PublicSubnet1Cidr
            - Ref: PublicSubnet2Cidr
  IamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-2.amazonaws.com/cfn-workshop-s3-s3bucket-1xluv23n1twtc/6bb91d577527b016b1275ebf74d515d8.template
      TimeoutInMinutes: 10
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-2.amazonaws.com/cfn-workshop-s3-s3bucket-1xluv23n1twtc/8263a6a6a2fefcf87db03be990f303b1.template
      TimeoutInMinutes: 20
      Parameters:
        EnvironmentType:
          Ref: EnvironmentType
        VpcId:
          Fn::GetAtt:
          - VpcStack
          - Outputs.VpcId
        SubnetId:
          Fn::GetAtt:
          - VpcStack
          - Outputs.PublicSubnet1
        WebServerInstanceProfile:
          Fn::GetAtt:
          - IamStack
          - Outputs.WebServerInstanceProfile
